<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CircuitoComunalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * 
     * Circuitos Comunales organizados por Parroquia:
     * - Escuque (parroquia_id: 1)
     * - Sabana Libre (parroquia_id: 2)
     * - La Unión (parroquia_id: 3)
     * - Santa Rita (parroquia_id: 4)
     */
    public function run(): void
    {
        \DB::table('circuito_comunals')->delete();
        
        \DB::table('circuito_comunals')->insert(array(
            // ========================================
            // PARROQUIA ESCUQUE (parroquia_id: 1)
            // ========================================
            
            // COMUNA: FUERZA DEL CAMPO (14 CC)
            // Centro Electoral: Unidad Educativa Santa Rosa
            // Sector: El Mamon
            
            0 => array(
                'id' => 1,
                'parroquia_id' => 1,
                'nombre' => 'Jirajara parte Baja',
                'codigo' => 'CC-ESC-001',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            1 => array(
                'id' => 2,
                'parroquia_id' => 1,
                'nombre' => 'Caficultores jirajarenses',
                'codigo' => 'CC-ESC-002',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            2 => array(
                'id' => 3,
                'parroquia_id' => 1,
                'nombre' => 'Jirajara parte Alta',
                'codigo' => 'CC-ESC-003',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            3 => array(
                'id' => 4,
                'parroquia_id' => 1,
                'nombre' => 'Macarena',
                'codigo' => 'CC-ESC-004',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            4 => array(
                'id' => 5,
                'parroquia_id' => 1,
                'nombre' => 'El Pedregal',
                'codigo' => 'CC-ESC-005',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            5 => array(
                'id' => 6,
                'parroquia_id' => 1,
                'nombre' => 'La Reserva del Campesino',
                'codigo' => 'CC-ESC-006',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            6 => array(
                'id' => 7,
                'parroquia_id' => 1,
                'nombre' => 'Pan de Azúcar',
                'codigo' => 'CC-ESC-007',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            7 => array(
                'id' => 8,
                'parroquia_id' => 1,
                'nombre' => 'Sabaneta Unida',
                'codigo' => 'CC-ESC-008',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            8 => array(
                'id' => 9,
                'parroquia_id' => 1,
                'nombre' => 'Sicoque',
                'codigo' => 'CC-ESC-009',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            9 => array(
                'id' => 10,
                'parroquia_id' => 1,
                'nombre' => 'El Colorado',
                'codigo' => 'CC-ESC-010',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            10 => array(
                'id' => 11,
                'parroquia_id' => 1,
                'nombre' => 'Lindo Potreritos de Escuque',
                'codigo' => 'CC-ESC-011',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            11 => array(
                'id' => 12,
                'parroquia_id' => 1,
                'nombre' => 'La Honda',
                'codigo' => 'CC-ESC-012',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            12 => array(
                'id' => 13,
                'parroquia_id' => 1,
                'nombre' => 'Candelilla el Refugio Divino',
                'codigo' => 'CC-ESC-013',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            13 => array(
                'id' => 14,
                'parroquia_id' => 1,
                'nombre' => 'La Montañita',
                'codigo' => 'CC-ESC-014',
                'descripcion' => 'Comuna: Fuerza del Campo | Centro Electoral: Unidad Educativa Santa Rosa | Sector: El Mamon',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            
            // COMUNA: MANUELITA SÁENZ (14 CC)
            // Centro Electoral: Preescolar Sopotocientos
            // Sector: Urbanización Fray Ignacio Álvarez
            
            24 => array(
                'id' => 25,
                'parroquia_id' => 1,
                'nombre' => 'Puerto Escondido',
                'codigo' => 'CC-ESC-015',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            25 => array(
                'id' => 26,
                'parroquia_id' => 1,
                'nombre' => 'Valle Alto',
                'codigo' => 'CC-ESC-016',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            26 => array(
                'id' => 27,
                'parroquia_id' => 1,
                'nombre' => 'La Garita',
                'codigo' => 'CC-ESC-017',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            27 => array(
                'id' => 28,
                'parroquia_id' => 1,
                'nombre' => 'Unidos por Siempre',
                'codigo' => 'CC-ESC-018',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            28 => array(
                'id' => 29,
                'parroquia_id' => 1,
                'nombre' => 'Tierra de Nubes',
                'codigo' => 'CC-ESC-019',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            29 => array(
                'id' => 30,
                'parroquia_id' => 1,
                'nombre' => 'Fray Ignacio Álvarez',
                'codigo' => 'CC-ESC-020',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            30 => array(
                'id' => 31,
                'parroquia_id' => 1,
                'nombre' => 'San Francisco',
                'codigo' => 'CC-ESC-021',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            31 => array(
                'id' => 32,
                'parroquia_id' => 1,
                'nombre' => 'Francisco Urdaneta',
                'codigo' => 'CC-ESC-022',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            32 => array(
                'id' => 33,
                'parroquia_id' => 1,
                'nombre' => 'Divino Valle',
                'codigo' => 'CC-ESC-023',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            33 => array(
                'id' => 34,
                'parroquia_id' => 1,
                'nombre' => 'Progresando Juntos',
                'codigo' => 'CC-ESC-024',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            34 => array(
                'id' => 35,
                'parroquia_id' => 1,
                'nombre' => 'Francisco Pipo Sarache',
                'codigo' => 'CC-ESC-025',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            35 => array(
                'id' => 36,
                'parroquia_id' => 1,
                'nombre' => 'El Corozo',
                'codigo' => 'CC-ESC-026',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            36 => array(
                'id' => 37,
                'parroquia_id' => 1,
                'nombre' => 'Tabisque y la Legua',
                'codigo' => 'CC-ESC-027',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            37 => array(
                'id' => 38,
                'parroquia_id' => 1,
                'nombre' => 'Esperanza Nueva',
                'codigo' => 'CC-ESC-028',
                'descripcion' => 'Comuna: Manuelita Sáenz | Centro Electoral: Preescolar Sopotocientos | Sector: Urbanización Fray Ignacio Álvarez',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            
            
            // COMUNA: DIOSA IKAKE (16 CC)
            // Centro Electoral: Grupo Escolar Eduardo Blanco
            // Sector: Calle Parte Alta
            
            38 => array(
                'id' => 39,
                'parroquia_id' => 1,
                'nombre' => 'Media Luna',
                'codigo' => 'CC-ESC-029',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            39 => array(
                'id' => 40,
                'parroquia_id' => 1,
                'nombre' => 'Francisco Ruiz',
                'codigo' => 'CC-ESC-030',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            40 => array(
                'id' => 41,
                'parroquia_id' => 1,
                'nombre' => 'Eloísa Torres',
                'codigo' => 'CC-ESC-031',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            41 => array(
                'id' => 42,
                'parroquia_id' => 1,
                'nombre' => 'Diosa Ikake',
                'codigo' => 'CC-ESC-032',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            42 => array(
                'id' => 43,
                'parroquia_id' => 1,
                'nombre' => 'El Golondrino',
                'codigo' => 'CC-ESC-033',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            43 => array(
                'id' => 44,
                'parroquia_id' => 1,
                'nombre' => 'Brisas de las Rosas',
                'codigo' => 'CC-ESC-034',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            44 => array(
                'id' => 45,
                'parroquia_id' => 1,
                'nombre' => 'Hombre del Anillo',
                'codigo' => 'CC-ESC-035',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            45 => array(
                'id' => 46,
                'parroquia_id' => 1,
                'nombre' => 'Tendal y las Rosas',
                'codigo' => 'CC-ESC-036',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            46 => array(
                'id' => 47,
                'parroquia_id' => 1,
                'nombre' => 'Las Delicias p/a',
                'codigo' => 'CC-ESC-037',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            47 => array(
                'id' => 48,
                'parroquia_id' => 1,
                'nombre' => 'Delicias p/b',
                'codigo' => 'CC-ESC-038',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            48 => array(
                'id' => 49,
                'parroquia_id' => 1,
                'nombre' => 'La Loma',
                'codigo' => 'CC-ESC-039',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            49 => array(
                'id' => 50,
                'parroquia_id' => 1,
                'nombre' => 'Los Jurumas',
                'codigo' => 'CC-ESC-040',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            50 => array(
                'id' => 51,
                'parroquia_id' => 1,
                'nombre' => 'La Victoria',
                'codigo' => 'CC-ESC-041',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            51 => array(
                'id' => 52,
                'parroquia_id' => 1,
                'nombre' => 'Paz, Bienestar y Felicidad',
                'codigo' => 'CC-ESC-042',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            52 => array(
                'id' => 53,
                'parroquia_id' => 1,
                'nombre' => 'Calle Nueva',
                'codigo' => 'CC-ESC-043',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            53 => array(
                'id' => 54,
                'parroquia_id' => 1,
                'nombre' => 'Mismote',
                'codigo' => 'CC-ESC-044',
                'descripcion' => 'Comuna: Diosa Ikake | Centro Electoral: Grupo Escolar Eduardo Blanco | Sector: Calle Parte Alta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            
            // ========================================
            // PARROQUIA SABANA LIBRE (parroquia_id: 2)
            // ========================================
            
            // COMUNA: SAN MIGUEL ARCÁNGEL (12 CC)
            // Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado
            // Sector: Grupo Escolar
            
            54 => array(
                'id' => 55,
                'parroquia_id' => 2,
                'nombre' => 'Pensil Parte Alta',
                'codigo' => 'CC-SAB-001',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            65 => array(
                'id' => 66,
                'parroquia_id' => 2,
                'nombre' => 'Pensil Parte Media Unidos de Venezuela',
                'codigo' => 'CC-SAB-002',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            66 => array(
                'id' => 67,
                'parroquia_id' => 2,
                'nombre' => 'Pensil Parte Baja Rosa Mística',
                'codigo' => 'CC-SAB-003',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            67 => array(
                'id' => 68,
                'parroquia_id' => 2,
                'nombre' => 'El Playón',
                'codigo' => 'CC-SAB-004',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            68 => array(
                'id' => 69,
                'parroquia_id' => 2,
                'nombre' => 'Renacer Bolivariano',
                'codigo' => 'CC-SAB-005',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            69 => array(
                'id' => 70,
                'parroquia_id' => 2,
                'nombre' => 'Don Beltrán Antonio Viloria',
                'codigo' => 'CC-SAB-006',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            70 => array(
                'id' => 71,
                'parroquia_id' => 2,
                'nombre' => 'La Sabana',
                'codigo' => 'CC-SAB-007',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            71 => array(
                'id' => 72,
                'parroquia_id' => 2,
                'nombre' => 'Los Canaletes',
                'codigo' => 'CC-SAB-008',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            72 => array(
                'id' => 73,
                'parroquia_id' => 2,
                'nombre' => 'Los Pinos',
                'codigo' => 'CC-SAB-009',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            73 => array(
                'id' => 74,
                'parroquia_id' => 2,
                'nombre' => 'Sabana Libre',
                'codigo' => 'CC-SAB-010',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            74 => array(
                'id' => 75,
                'parroquia_id' => 2,
                'nombre' => 'Vista Hermosa',
                'codigo' => 'CC-SAB-011',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            75 => array(
                'id' => 76,
                'parroquia_id' => 2,
                'nombre' => 'Pie de Ponemesa',
                'codigo' => 'CC-SAB-012',
                'descripcion' => 'Comuna: San Miguel Arcángel | Centro Electoral: Escuela Bolivariana Neptali Valero Hurtado | Sector: Grupo Escolar',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            
            // COMUNA: VIRGEN DE LA PAZ D (9 CC)
            // Centro Electoral: Escuela Estadal Concentrada Número 123
            // Sector: El Corocito
            
            76 => array(
                'id' => 77,
                'parroquia_id' => 2,
                'nombre' => 'La Laja',
                'codigo' => 'CC-SAB-013',
                'descripcion' => 'Comuna: Virgen de la Paz D | Centro Electoral: Escuela Estadal Concentrada Número 123 | Sector: El Corocito',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            77 => array(
                'id' => 78,
                'parroquia_id' => 2,
                'nombre' => 'La Popa',
                'codigo' => 'CC-SAB-014',
                'descripcion' => 'Comuna: Virgen de la Paz D | Centro Electoral: Escuela Estadal Concentrada Número 123 | Sector: El Corocito',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            78 => array(
                'id' => 79,
                'parroquia_id' => 2,
                'nombre' => 'Las Cruces de la Unión',
                'codigo' => 'CC-SAB-015',
                'descripcion' => 'Comuna: Virgen de la Paz D | Centro Electoral: Escuela Estadal Concentrada Número 123 | Sector: El Corocito',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            79 => array(
                'id' => 80,
                'parroquia_id' => 2,
                'nombre' => 'Agua Dulce',
                'codigo' => 'CC-SAB-016',
                'descripcion' => 'Comuna: Virgen de la Paz D | Centro Electoral: Escuela Estadal Concentrada Número 123 | Sector: El Corocito',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            80 => array(
                'id' => 81,
                'parroquia_id' => 2,
                'nombre' => 'Corocito, la Pica, Agua Dulce',
                'codigo' => 'CC-SAB-017',
                'descripcion' => 'Comuna: Virgen de la Paz D | Centro Electoral: Escuela Estadal Concentrada Número 123 | Sector: El Corocito',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            81 => array(
                'id' => 82,
                'parroquia_id' => 2,
                'nombre' => 'La Pica',
                'codigo' => 'CC-SAB-018',
                'descripcion' => 'Comuna: Virgen de la Paz D | Centro Electoral: Escuela Estadal Concentrada Número 123 | Sector: El Corocito',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            82 => array(
                'id' => 83,
                'parroquia_id' => 2,
                'nombre' => 'Las Cruces de Medio Monte',
                'codigo' => 'CC-SAB-019',
                'descripcion' => 'Comuna: Virgen de la Paz D | Centro Electoral: Escuela Estadal Concentrada Número 123 | Sector: El Corocito',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            83 => array(
                'id' => 84,
                'parroquia_id' => 2,
                'nombre' => 'San Rafael Arcángel',
                'codigo' => 'CC-SAB-020',
                'descripcion' => 'Comuna: Virgen de la Paz D | Centro Electoral: Escuela Estadal Concentrada Número 123 | Sector: El Corocito',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            84 => array(
                'id' => 85,
                'parroquia_id' => 2,
                'nombre' => 'Santa María Lamedero',
                'codigo' => 'CC-SAB-021',
                'descripcion' => 'Comuna: Virgen de la Paz D | Centro Electoral: Escuela Estadal Concentrada Número 123 | Sector: El Corocito',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            
            // ========================================
            // PARROQUIA LA UNIÓN (parroquia_id: 3)
            // ========================================
            
            // COMUNA: UNIÓN SOCIALISTA (10 CC)
            // Centro Electoral: Escuela Bolivariana Esteban Rasquin
            // Sector: La Laguneta
            
            14 => array(
                'id' => 15,
                'parroquia_id' => 3,
                'nombre' => 'Unidos por las Rurales y San Benito',
                'codigo' => 'CC-LUN-001',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            15 => array(
                'id' => 16,
                'parroquia_id' => 3,
                'nombre' => 'La Laguneta',
                'codigo' => 'CC-LUN-002',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            16 => array(
                'id' => 17,
                'parroquia_id' => 3,
                'nombre' => 'El Boquerón',
                'codigo' => 'CC-LUN-003',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            17 => array(
                'id' => 18,
                'parroquia_id' => 3,
                'nombre' => 'Divino Niño',
                'codigo' => 'CC-LUN-004',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            18 => array(
                'id' => 19,
                'parroquia_id' => 3,
                'nombre' => 'El Alba',
                'codigo' => 'CC-LUN-005',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            19 => array(
                'id' => 20,
                'parroquia_id' => 3,
                'nombre' => 'El Alto, Mirabel y Las Casitas',
                'codigo' => 'CC-LUN-006',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            20 => array(
                'id' => 21,
                'parroquia_id' => 3,
                'nombre' => 'Unión y Fuerza',
                'codigo' => 'CC-LUN-007',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            21 => array(
                'id' => 22,
                'parroquia_id' => 3,
                'nombre' => 'Quevedo',
                'codigo' => 'CC-LUN-008',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            22 => array(
                'id' => 23,
                'parroquia_id' => 3,
                'nombre' => 'Juan Díaz',
                'codigo' => 'CC-LUN-009',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            23 => array(
                'id' => 24,
                'parroquia_id' => 3,
                'nombre' => 'El Progreso',
                'codigo' => 'CC-LUN-010',
                'descripcion' => 'Comuna: Unión Socialista | Centro Electoral: Escuela Bolivariana Esteban Rasquin | Sector: La Laguneta',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            
            // ========================================
            // PARROQUIA SANTA RITA (parroquia_id: 4)
            // ========================================
            
            // COMUNA: FLORESTA EN MARCHA C (10 CC)
            // Centro Electoral: Unidad Educativa Rural La Mata
            // Sector: La Mata
            
            85 => array(
                'id' => 86,
                'parroquia_id' => 4,
                'nombre' => 'Colinas de Segovia 200',
                'codigo' => 'CC-SRT-001',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            86 => array(
                'id' => 87,
                'parroquia_id' => 4,
                'nombre' => 'Conucos de la Paz',
                'codigo' => 'CC-SRT-002',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            87 => array(
                'id' => 88,
                'parroquia_id' => 4,
                'nombre' => 'Las Dalias',
                'codigo' => 'CC-SRT-003',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            88 => array(
                'id' => 89,
                'parroquia_id' => 4,
                'nombre' => 'San José',
                'codigo' => 'CC-SRT-004',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            89 => array(
                'id' => 90,
                'parroquia_id' => 4,
                'nombre' => 'Santa Rita la Mata',
                'codigo' => 'CC-SRT-005',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            90 => array(
                'id' => 91,
                'parroquia_id' => 4,
                'nombre' => 'Renacer de Terrazas',
                'codigo' => 'CC-SRT-006',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            91 => array(
                'id' => 92,
                'parroquia_id' => 4,
                'nombre' => 'Comunidad Ecológica Ezequiel Zamora',
                'codigo' => 'CC-SRT-007',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            92 => array(
                'id' => 93,
                'parroquia_id' => 4,
                'nombre' => 'Urbanización Unidas Hugo Chávez',
                'codigo' => 'CC-SRT-008',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            93 => array(
                'id' => 94,
                'parroquia_id' => 4,
                'nombre' => 'Indio Jaruma',
                'codigo' => 'CC-SRT-009',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
            94 => array(
                'id' => 95,
                'parroquia_id' => 4,
                'nombre' => 'Colinas de Carmanía',
                'codigo' => 'CC-SRT-010',
                'descripcion' => 'Comuna: Floresta en Marcha C | Centro Electoral: Unidad Educativa Rural La Mata | Sector: La Mata',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ),
        ));
    }
}
