<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            /* Settings de la moneda */
            [
                'key' => 'currency_code',
                'value' => 'USD',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Código de Moneda',
                'description' => 'Código ISO de la moneda principal del sistema (USD, EUR, etc.)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'currency_symbol',
                'value' => '$',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Símbolo de Moneda',
                'description' => 'Símbolo para mostrar junto a los montos ($, €, etc.)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'currency_position',
                'value' => 'before',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Posición del Símbolo',
                'description' => 'Posición del símbolo de moneda (before: $100, after: 100$)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'available_currencies',
                'value' => json_encode([
                    ['code' => 'USD', 'symbol' => '$', 'name' => 'Dólar Estadounidense'],
                    ['code' => 'EUR', 'symbol' => '€', 'name' => 'Euro'],
                    ['code' => 'GBP', 'symbol' => '£', 'name' => 'Libra Esterlina'],
                    ['code' => 'VES', 'symbol' => 'Bs.', 'name' => 'Bolívar Digital'],
                ]),
                'type' => 'json',
                'group' => 'currency',
                'name' => 'Monedas Disponibles',
                'description' => 'Lista de monedas disponibles en el sistema',
                'is_public' => true,
                'is_tenant_editable' => false,
            ],
            [
                'key' => 'decimal_separator',
                'value' => '.',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Separador Decimal',
                'description' => 'Carácter usado como separador decimal (. o ,)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'thousand_separator',
                'value' => ',',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Separador de Miles',
                'description' => 'Carácter usado como separador de miles (, o .)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],

            /* Settings generales de la empresa */
            [
                'key' => 'name',
                'value' => 'OPTIRANGO',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Nombre de la Empresa',
                'description' => 'Nombre de la empresa que se mostrará en la interfaz',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'razon_social',
                'value' => 'OPTIRANGO, C.A.',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Razón Social',
                'description' => 'Razón social de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'rif',
                'value' => 'J-505868454',
                'type' => 'string',
                'group' => 'general',
                'name' => 'RIF',
                'description' => 'RIF de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'direccion_fiscal',
                'value' => 'AV. URDANETA ESQ PELOTA EDIF CENTRO PROFESIONAL URDANETA',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Dirección Fiscal',
                'description' => 'Dirección fiscal de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'description',
                'value' => 'Más que una óptica...',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Descripción',
                'description' => 'Descripción de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'long_description',
                'value' => 'En Ópti Rango, nos dedicamos a ofrecer soluciones visuales de la más alta calidad. Con años de experiencia y un equipo de profesionales comprometidos, garantizamos una atención personalizada y productos que se adaptan a tus necesidades y estilo de vida.',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Descripción Larga',
                'description' => 'Descripción larga de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'oficina_principal',
                'value' => 'Oficina Principal',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Oficina Principal',
                'description' => 'Oficina principal de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'ciudad',
                'value' => 'Caracas',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Ciudad',
                'description' => 'Ciudad de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'latitude',
                'value' => '10.50731922701982',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Latitud',
                'description' => 'Latitud de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'longitude',
                'value' => '-66.9116931537826',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Longitud',
                'description' => 'Longitud de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'horario_atencion',
                'value' => 'Lunes a Viernes de 8:00 a 17:00',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Horario de Atención',
                'description' => 'Horario de atención de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'telefono_principal',
                'value' => '+584246406797',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Teléfono Principal',
                'description' => 'Teléfono principal de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'telefono_secundario',
                'value' => '+584126426797',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Teléfono Secundario',
                'description' => 'Teléfono secundario de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'email_principal',
                'value' => 'jhonnytorresforro@gmail.com',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Email Principal',
                'description' => 'Email principal de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'email_secundario',
                'value' => 'silvio.ramirez.m@gmail.com',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Email Secundario',
                'description' => 'Email secundario de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'domain',
                'value' => 'optirango.nevora.app',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Dominio',
                'description' => 'Dominio de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'actividad',
                'value' => 'Optica',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Actividad',
                'description' => 'Actividad de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'servicios',
                'value' => json_encode([
                    ['icon' => 'fa-solid fa-lightbulb', 'color' => 'blue', 'title' => 'Innovación Primero', 'description' => 'Utilizamos investigación de vanguardia con métodos de aprendizaje avanzados para crear tecnología revolucionaria.'],
                    ['icon' => 'fa-solid fa-users', 'color' => 'green', 'title' => 'Espíritu Colaborativo', 'description' => 'Nuestra diversidad de talentos se centra en cooperaciones de colaboración para evaluar y crear soluciones empresariales.'],
                    ['icon' => 'fa-solid fa-handshake', 'color' => 'blue', 'title' => 'Integridad y Confianza', 'description' => 'Nuestros desarrollos transparentes son diseñados para lograr el desarrollo ético sostenible en el negocio óptico.'],
                ]),
                'type' => 'json',
                'group' => 'general',
                'name' => 'Servicios',
                'description' => 'Lista de servicios disponibles en el sistema',
                'is_public' => true,
                'is_tenant_editable' => false,
            ],

            /* Settings de los logos */

            [
                'key' => 'logo',
                'value' => 'images/1_logo.png',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_background_solid',
                'value' => 'images/2_logo_background_solid.png',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Background Solid',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_grey',
                'value' => 'images/3_logo_grey.png',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Grey',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_horizontal',
                'value' => 'images/4_logo_horizontal.png',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Horizontal',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_horizontal_background_solid',
                'value' => 'images/5_logo_horizontal_background_solid.jpg',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Horizontal Background Solid',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_icon',
                'value' => 'images/6_logo_icon.png',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Icon',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_icon_grey',
                'value' => 'images/7_logo_icon_grey.png',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Icon Grey',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],

        ];

        foreach ($settings as $setting) {
            Setting::create($setting);
        }
    }
}
