<?php

namespace Database\Seeders;

use App\Models\Setting;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $settings = [
            /* Settings de la moneda */
            [
                'key' => 'currency_code',
                'value' => 'USD',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Código de Moneda',
                'description' => 'Código ISO de la moneda principal del sistema (USD, EUR, etc.)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'currency_symbol',
                'value' => '$',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Símbolo de Moneda',
                'description' => 'Símbolo para mostrar junto a los montos ($, €, etc.)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'currency_position',
                'value' => 'before',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Posición del Símbolo',
                'description' => 'Posición del símbolo de moneda (before: $100, after: 100$)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'available_currencies',
                'value' => json_encode([
                    ['code' => 'USD', 'symbol' => '$', 'name' => 'Dólar Estadounidense'],
                    ['code' => 'EUR', 'symbol' => '€', 'name' => 'Euro'],
                    ['code' => 'GBP', 'symbol' => '£', 'name' => 'Libra Esterlina'],
                    ['code' => 'VES', 'symbol' => 'Bs.', 'name' => 'Bolívar Digital'],
                ]),
                'type' => 'json',
                'group' => 'currency',
                'name' => 'Monedas Disponibles',
                'description' => 'Lista de monedas disponibles en el sistema',
                'is_public' => true,
                'is_tenant_editable' => false,
            ],
            [
                'key' => 'decimal_separator',
                'value' => '.',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Separador Decimal',
                'description' => 'Carácter usado como separador decimal (. o ,)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'thousand_separator',
                'value' => ',',
                'type' => 'string',
                'group' => 'currency',
                'name' => 'Separador de Miles',
                'description' => 'Carácter usado como separador de miles (, o .)',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],

            /* Settings generales de la empresa */
            [
                'key' => 'name',
                'value' => 'Sistema Web de Gestion de la Alcaldia del Municipio Escuque',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Nombre de la Empresa',
                'description' => 'Nombre de la empresa que se mostrará en la interfaz',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'razon_social',
                'value' => 'Sistema Web de Gestion de la Alcaldia del Municipio Escuque',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Razón Social',
                'description' => 'Razón social de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'rif',
                'value' => 'J-505868454',
                'type' => 'string',
                'group' => 'general',
                'name' => 'RIF',
                'description' => 'RIF de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'direccion_fiscal',
                'value' => 'Avenida principal, Municipio Escuque, Estado Trujillo.',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Dirección Fiscal',
                'description' => 'Dirección fiscal de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'description',
                'value' => 'Sistema de control de beneficios sociales',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Descripción',
                'description' => 'Descripción de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'long_description',
                'value' => 'Sistema Web de Gestion de la Alcaldia del Municipio Escuque es un sistema integral para la gestión y control de beneficios sociales. Facilitamos la administración eficiente de programas de ayuda social, garantizando transparencia y acceso equitativo a los beneficiarios.',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Descripción Larga',
                'description' => 'Descripción larga de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'oficina_principal',
                'value' => 'Oficina Principal',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Oficina Principal',
                'description' => 'Oficina principal de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'ciudad',
                'value' => 'Caracas',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Ciudad',
                'description' => 'Ciudad de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'latitude',
                'value' => '10.50731922701982',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Latitud',
                'description' => 'Latitud de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'longitude',
                'value' => '-66.9116931537826',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Longitud',
                'description' => 'Longitud de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'horario_atencion',
                'value' => 'Lunes a Viernes de 8:00 a 17:00',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Horario de Atención',
                'description' => 'Horario de atención de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'telefono_principal',
                'value' => '04163762183',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Teléfono Principal',
                'description' => 'Teléfono principal de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'telefono_secundario',
                'value' => '04163762183',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Teléfono Secundario',
                'description' => 'Teléfono secundario de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'email_principal',
                'value' => 'ag@gmail.com',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Email Principal',
                'description' => 'Email principal de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'email_secundario',
                'value' => 'alejandro@admin.com',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Email Secundario',
                'description' => 'Email secundario de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'domain',
                'value' => 'escuque.nevora.app',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Dominio',
                'description' => 'Dominio de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'actividad',
                'value' => 'Control de Beneficios Sociales',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Actividad',
                'description' => 'Actividad de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'servicios',
                'value' => json_encode([
                    ['icon' => 'fa-solid fa-hands-helping', 'color' => 'blue', 'title' => 'Gestión Eficiente', 'description' => 'Sistema integral para la administración y control de beneficios sociales con tecnología de vanguardia.'],
                    ['icon' => 'fa-solid fa-users', 'color' => 'green', 'title' => 'Atención Personalizada', 'description' => 'Enfoque centrado en las necesidades de cada beneficiario, garantizando un servicio de calidad.'],
                    ['icon' => 'fa-solid fa-shield-alt', 'color' => 'blue', 'title' => 'Transparencia y Confianza', 'description' => 'Procesos transparentes y seguros para garantizar el acceso equitativo a los beneficios sociales.'],
                ]),
                'type' => 'json',
                'group' => 'general',
                'name' => 'Servicios',
                'description' => 'Lista de servicios disponibles en el sistema',
                'is_public' => true,
                'is_tenant_editable' => false,
            ],

            /* Settings de los logos */

            [
                'key' => 'logo',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_background_solid',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Background Solid',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_grey',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Grey',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_horizontal',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Horizontal',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_horizontal_background_solid',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Horizontal Background Solid',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_icon',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Icon',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],
            [
                'key' => 'logo_icon_grey',
                'value' => '',
                'type' => 'string',
                'group' => 'general',
                'name' => 'Logo Icon Grey',
                'description' => 'Logo de la empresa',
                'is_public' => true,
                'is_tenant_editable' => true,
            ],

        ];

        foreach ($settings as $setting) {
            Setting::create($setting);
        }
    }
}
